### ISSUE TITLE
TypeScript error on Build 

### ISSUE THREAD

**Issue by vasco3** [crcn/tandem-old#399]
Using node v7.5
when running `npm run build` I get the following error:

```

75   private async pump(cursor: Cursor, writer: WritableStreamDefaultWriter<any>) {
                                ~~~~~~

src/@tandem/mesh/ds/mongo.ts(75,30): error TS2314: Generic type 'Cursor<T>' requires 1 type argument(s).

[15:57:37] 'build:typescript' errored after 14 s
[15:57:37] Error: 2
    at formatError (/Users/cuadraman/Documents/Code/tandem/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/cuadraman/Documents/Code/tandem/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:189:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/cuadraman/Documents/Code/tandem/node_modules/orchestrator/index.js:264:8)
    at /Users/cuadraman/Documents/Code/tandem/node_modules/orchestrator/index.js:275:23
    at finish (/Users/cuadraman/Documents/Code/tandem/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/cuadraman/Documents/Code/tandem/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
```

**Comment by crcn** [comment]
This may be an issue with an improper version of `@types/mongodb`. Try installing `@types/mongodb@2.1.37` and see if that fixes the issue.

**Comment by vasco3** [comment]
That worked! thanks for the quick response
