### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by markthepixel** [crcn/tandem-old#406]
> Unable to find Electron app at /Users/mprogano/labs/tandem/dist/index.bundle.js
> Cannot find module '/Users/mprogano/labs/tandem/dist/index.bundle.js'

---

```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "code" "workspace.tandem"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! tandemapp@1.0.5 code: `DEV=1 SANDBOXED=1 electron dist/index.bundle.js "workspace.tandem"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tandemapp@1.0.5 code script 'DEV=1 SANDBOXED=1 electron dist/index.bundle.js "workspace.tandem"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tandemapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEV=1 SANDBOXED=1 electron dist/index.bundle.js "workspace.tandem"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tandemapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tandemapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mprogano/labs/tandem/npm-debug.log
mprogano:mprogano tandem [master] $ 
```

---

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'code',
1 verbose cli   'workspace.tandem' ]
2 info using npm@4.1.2
3 info using node@v7.6.0
4 verbose run-script [ 'precode', 'code', 'postcode' ]
5 info lifecycle tandemapp@1.0.5~precode: tandemapp@1.0.5
6 silly lifecycle tandemapp@1.0.5~precode: no script for precode, continuing
7 info lifecycle tandemapp@1.0.5~code: tandemapp@1.0.5
8 verbose lifecycle tandemapp@1.0.5~code: unsafe-perm in lifecycle true
9 verbose lifecycle tandemapp@1.0.5~code: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mprogano/labs/tandem/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle tandemapp@1.0.5~code: CWD: /Users/mprogano/labs/tandem
11 silly lifecycle tandemapp@1.0.5~code: Args: [ '-c',
11 silly lifecycle   'DEV=1 SANDBOXED=1 electron dist/index.bundle.js "workspace.tandem"' ]
12 silly lifecycle tandemapp@1.0.5~code: Returned: code: 1  signal: null
13 info lifecycle tandemapp@1.0.5~code: Failed to exec code script
14 verbose stack Error: tandemapp@1.0.5 code: `DEV=1 SANDBOXED=1 electron dist/index.bundle.js "workspace.tandem"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid tandemapp@1.0.5
16 verbose cwd /Users/mprogano/labs/tandem
17 error Darwin 16.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "code" "workspace.tandem"
19 error node v7.6.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error tandemapp@1.0.5 code: `DEV=1 SANDBOXED=1 electron dist/index.bundle.js "workspace.tandem"`
22 error Exit status 1
23 error Failed at the tandemapp@1.0.5 code script 'DEV=1 SANDBOXED=1 electron dist/index.bundle.js "workspace.tandem"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the tandemapp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     DEV=1 SANDBOXED=1 electron dist/index.bundle.js "workspace.tandem"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs tandemapp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls tandemapp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by crcn** [comment]
Thanks for catching that. There have been a few edges around building Tandem locally, so I'll probably setup a Docker container to make the setup process a bit easier. Here's the ticket for that: #405. 

In the meantime, what version of Node & NPM are you using?

**Comment by harlequin78** [comment]
Is there any progress?

**Comment by LDubya** [comment]
Hi, I've also been having this issue. Never got the app to run. How can we fix this? Using NVM I used the proper version of node as requested in the documentation.

**Comment by crcn** [comment]
Yep, this should be fixed with #405 once I get around to it - likely sometime in the next few weeks.

**Comment by LDubya** [comment]
Hi @crcn just wanted to check if there are any tips on how to get this working before you upload a new build? Just need to know what to do even if it's a bit complicated

**Comment by crcn** [comment]
Nothing yet @LDubya, there are number of other issues that are taking priority right now, particularly modularizing Tandem so that parts of the core can be used in other contexts. Once I have those parts stable, then I'll move forward with bug fixes in Tandem.  Sorry I don't have a quick fix for you -- I'd love to get most of these showstoppers out of the way so that people can play with the app, but the development of this thing is massive with only one guy (me) maintaining it.

**Comment by crcn** [comment]
Closing this ticket since Tandem has been entirely revamped, and no longer uses electron (it'll be a text editor extension).
